export const senderCopy = {
  "title": "เพิ่มข้อมูลผู้ส่ง",
  "subtitle": "กรอกข้อมูลผู้ส่งสำหรับลงทะเบียนพัสดุ",
  "labelName": "ชื่อ",
  "placeholderName": "ชื่อ-นามสกุล",
  "labelPhone": "เบอร์โทรศัพท์",
  "placeholderPhone": "08xxxxxxxx หรือ +66...",
  "labelAddress": "ที่อยู่",
  "placeholderAddress": "บ้านเลขที่ ซอย ถนน",
  "labelLocation": "ตำบล / อำเภอ / จังหวัด / รหัสไปรษณีย์",
  "hintLocation": "พิมพ์เพื่อค้นหา แล้วเลือกจากรายการ (รวมเป็นฟิลด์เดียว)",
  "placeholderLocation": "เช่น บางรัก หรือ 10200",
  "searching": "กำลังค้นหา...",
  "loadingForm": "กำลังโหลด...",
  "noResults": "ไม่พบผลลัพธ์",
  "checkboxPrimary": "ตั้งเป็นบัญชีหลัก",
  "save": "บันทึก",
  "back": "กลับ",
  "errName": "กรุณากรอกชื่อ",
  "errPhoneRequired": "กรุณากรอกเบอร์โทรศัพท์",
  "errPhoneFormat": "รูปแบบเบอร์โทรไม่ถูกต้อง",
  "errAddress": "กรุณากรอกที่อยู่",
  "errLocation": "กรุณาเลือกตำบล อำเภอ จังหวัด และรหัสไปรษณีย์จากรายการค้นหา",
  "titleEdit": "แก้ไขข้อมูลผู้ส่ง",
  "saving": "กำลังบันทึก...",
  "errSave": "บันทึกไม่สำเร็จ ลองใหม่อีกครั้ง",
  "errLoad": "โหลดข้อมูลไม่ได้",
  "errAuth": "กรุณาเข้าสู่ระบบใหม่"
} as const;
