export const recipientCopy = {
  title: "เพิ่มข้อมูลผู้รับ",
  subtitle: "กรอกข้อมูลผู้รับสำหรับลงทะเบียนพัสดุ",
  labelName: "ชื่อ",
  placeholderName: "ชื่อ-นามสกุล",
  labelPhone: "เบอร์โทรศัพท์",
  placeholderPhone: "เช่น 0812345678",
  labelAddress: "ที่อยู่",
  placeholderAddress: "บ้านเลขที่ ซอย ถนน",
  labelLocation: "ตำบล / อำเภอ / จังหวัด / รหัสไปรษณีย์",
  hintLocation: "พิมพ์เพื่อค้นหา แล้วเลือกจากรายการ (รวมเป็นฟิลด์เดียว)",
  placeholderLocation: "เช่น บางรัก หรือ 10200",
  searching: "กำลังค้นหา...",
  loadingForm: "กำลังโหลด...",
  noResults: "ไม่พบผลลัพธ์",
  checkboxSaveAddress: "บันทึกที่อยู่นี้",
  save: "บันทึก",
  back: "กลับ",
  errName: "กรุณากรอกชื่อ",
  errPhoneRequired: "กรุณากรอกเบอร์โทรศัพท์",
  errPhoneFormat: "กรุณากรอกเบอร์โทรศัพท์ให้ถูกต้องในรูปแบบ 0xxxxxxxxx (เช่น 0812345678)",
  errAddress: "กรุณากรอกที่อยู่",
  errLocation: "กรุณาเลือกตำบล อำเภอ จังหวัด และรหัสไปรษณีย์จากรายการค้นหา",
  titleEdit: "แก้ไขข้อมูลผู้รับ",
  saving: "กำลังบันทึก...",
  errSave: "บันทึกไม่สำเร็จ ลองใหม่อีกครั้ง",
  errLoad: "โหลดข้อมูลไม่ได้",
  errAuth: "กรุณาเข้าสู่ระบบใหม่",
} as const;
